apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=/workspace/Dockerfile"
      - "--context=/workspace"
      - "--destination=acrcloudhuntdev.azurecr.io/backend:1"
      - "--skip-tls-verify"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: workspace
        mountPath: /workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: acr-secret
    - name: workspace
      hostPath:
        path: /home/jihed/CloudJobHunt-Project/cloudjobhunt-backend
        type: Directory
